-fixed issues with INSTALL script -refreshing targets won't lose selected access point

diff --git a/trunk/grimwepa1.1/INSTALL b/trunk/grimwepa1.1/INSTALL
--- a/trunk/grimwepa1.1/INSTALL
+++ b/trunk/grimwepa1.1/INSTALL
@@ -1,3 +1,17 @@
-#!/bin/sh
+#!/bin/bash
+
+echo "compiling..."
+
 javac *.java
-jar cvfm grimwepa1.10a4.jar mymanifest *.class default_pw.txt README grimwepa.xpm gw_splash.jpg
+
+if [[ $? -eq 0  ]]
+then
+    echo "compiled successfully"
+	echo "building jar file..."
+    jar cvfm grimwepa1.10a4.jar mymanifest *.class default_pw.txt README grimwepa.xpm gw_splash.jpg >> /dev/null
+	echo "executing..."
+	echo ""
+    java -jar grimwepa1.10a4.jar $1
+else
+    echo "errors occurred while compiling"
+fi
